// Generated by https://quicktype.io

export interface CoursesResponse {
    ok:      boolean;
    courses: Course[];
}

export interface Course {
    _id:      string;
    name:     string;
    teacher?: string;
    time?:    number;
}

export interface SkillsResponse {
    ok:     boolean;
    skills: Skill[];
}

export interface Skill {
    _id:   string;
    image?: string;
    name:  string;
}

export interface ProyectResponse {
    proyects: Proyect[];
}

export interface Proyect {
    _id:      string;
    image:    string;
    languaje: string;
    name:     string;
}
